name: chartjs
version: 0.5.0-dev
description: Chart.js wrapper for Dart
author: Kevin Moore <kevmoo+github@google.com>
homepage: https://github.com/google/chartjs.dart/
environment:
  sdk: '>=1.13.1 <3.0.0'
dependencies:
  func: '>=0.1.0 <2.0.0'
  js: ^0.6.0
dev_dependencies:
  browser: ^0.10.0+2
